import { useEffect, useCallback } from "react";

// import { useErrorState } from "@/stores/errorState";
import { useLoader } from "../../store/loaderStore";
import { useOpenPopup } from "../../store/popupStore";

// import ErrorPopupMessage from "../ErrorPopupMessage/ErrorPopupMessage";
import CustomButton from "../CustomButton/CustomButton";

import "./Popup.scss";

const Popup: React.FC = () => {
    // constructing popup using other components
    // popupType: inform, form, submit
    // formComponent: some custom form
    // textComponent: text component to show in popup
    // size: screen size generated by useResize in parent component
    // setIsOpen: action from store
    const { popupType, formComponent, textComponent, size, setIsOpen } = useOpenPopup();

    const { isLoading } = useLoader();
    // const { message, code, cleanError } = useErrorState();

    const handleClosePopup = useCallback(() => {
        if (isLoading) {
            return;
        }
        setIsOpen(false, null);
        // cleanError();
    }, [isLoading, setIsOpen]);
    // esc listener to close popup
    useEffect(() => {
        function onKeyDown(evt: KeyboardEvent) {
            if (evt.key === "Escape" && !isLoading) {
                handleClosePopup();
            }
        }
        document.addEventListener("keydown", onKeyDown);
        return () => {
            document.removeEventListener("keydown", onKeyDown);
        };
    }, [isLoading, handleClosePopup]);

    return (
        // popup shadow with closeOnClick functionality
        <div className="popup__shadow" onClick={handleClosePopup}>
            <section className={`popup ${size}`} onClick={(e) => e.stopPropagation()}>
                <button
                    type="button"
                    className="popup__close"
                    aria-label="Close popup"
                    onClick={handleClosePopup}
                />
                <div className="popup__children">
                    {/* Creating popup with information (success/errors) */}
                    {/* {message ? (
                        <ErrorPopupMessage
                            message={message}
                        />
                    ) : (
                        <> */}
                    {/* Creating popup with information */}
                    {popupType === "inform" && (
                        <>
                            {textComponent}
                            <CustomButton type="button" text="Close" onClick={handleClosePopup} />
                        </>
                    )}

                    {/* Creating popup with form */}
                    {popupType === "form" && formComponent}

                    {/* Creating popup to get user submission */}
                    {popupType === "submit" && (
                        <>
                            {textComponent}
                            <CustomButton type="button" text="Submit" onClick={handleClosePopup} />
                            <CustomButton type="button" text="Cancel" onClick={handleClosePopup} />
                        </>
                    )}
                    {/* </>
                    )} */}
                </div>
            </section>
        </div>
    );
};
export default Popup;
